# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aEf9NYZqUAlbzze3D0DX-wPwoEeVAwDz
"""

import pandas as pd
import numpy as np
from google.colab import files

# ==========================================
# 1. 檔案讀取區
# ==========================================
# 讀取三個輔助投票模型
sub_m1 = pd.read_csv('0.97954.csv')
sub_m2 = pd.read_csv('0.98017.csv')
sub_m3 = pd.read_csv('0.98018.csv')

# 【最關鍵】：將你最高分的檔案設為 sub_best 防護網
sub_best = pd.read_csv('0.98030.csv')

# 確認所有檔案的資料列數量與 ID 排序完全一致
assert len(sub_m1) == len(sub_best), "檔案長度不一致！"
assert all(sub_m1['id'] == sub_best['id']), "ID 排序不一致，請檢查檔案！"

# 已經為你替換成正確的目標欄位名稱
TARGET_COL = 'Irrigation_Need'

# ==========================================
# 2. 條件投票 (Conditional Voting) 邏輯
# ==========================================
# 將三個基礎模型的預測結果合併在一起觀察
votes = pd.DataFrame({
    'm1': sub_m1[TARGET_COL],
    'm2': sub_m2[TARGET_COL],
    'm3': sub_m3[TARGET_COL]
})

# 判斷這三個輔助模型是否達成「完全共識」(預測值都一模一樣)
is_agreed = (votes.nunique(axis=1) == 1)

# ==========================================
# 3. 產生最終預測：共識決 + 防護網替換
# ==========================================
# 如果輔助模型有共識，就採用共識值；如果分歧，無條件信任最高分的 sub_best (0.98030.csv)
final_predictions = np.where(is_agreed, votes['m1'], sub_best[TARGET_COL])

# ==========================================
# 4. 輸出最終提交檔並自動下載
# ==========================================
submission = pd.DataFrame({
    'id': sub_best['id'],
    TARGET_COL: final_predictions
})

# 儲存在 Colab 虛擬機中
output_filename = 'ensemble_0_98030_boost.csv'
submission.to_csv(output_filename, index=False)

print(f"✅ 整合完成！總共 {len(submission)} 筆資料。")
print(f"🤝 其中有 {is_agreed.sum()} 筆資料達成共識。")
print(f"🛡️ 剩餘 {len(submission) - is_agreed.sum()} 筆分歧資料已由最高分模型 (0.98030) 接管。")

# 自動下載到個人電腦
files.download(output_filename)